---
deployment:
  tasks:
    - export DEPLOYPATH=/home/drynegr1/public_html/
    - export DEPLOYPATH2=/home/drynegr1/public_html/application/config/
    - export DEPLOYPATH3=/home/drynegr1/public_html/application/

    - /bin/cp -R /home/drynegr1/gitrepo/application/config/autoload.php $DEPLOYPATH2
    - /bin/cp -R /home/drynegr1/gitrepo/application/config/constants.php $DEPLOYPATH2
    - /bin/cp -R /home/drynegr1/gitrepo/application/config/doctypes.php $DEPLOYPATH2
    - /bin/cp -R /home/drynegr1/gitrepo/application/config/foreign_chars.php $DEPLOYPATH2
    - /bin/cp -R /home/drynegr1/gitrepo/application/config/hooks.php $DEPLOYPATH2
    - /bin/cp -R /home/drynegr1/gitrepo/application/config/index.html $DEPLOYPATH2
    - /bin/cp -R /home/drynegr1/gitrepo/application/config/memcached.php $DEPLOYPATH2
    - /bin/cp -R /home/drynegr1/gitrepo/application/config/migration.php $DEPLOYPATH2
    - /bin/cp -R /home/drynegr1/gitrepo/application/config/mimes.php $DEPLOYPATH2
    - /bin/cp -R /home/drynegr1/gitrepo/application/config/profiler.php $DEPLOYPATH2
    - /bin/cp -R /home/drynegr1/gitrepo/application/config/routes.php $DEPLOYPATH2
    - /bin/cp -R /home/drynegr1/gitrepo/application/config/smileys.php $DEPLOYPATH2
    - /bin/cp -R /home/drynegr1/gitrepo/application/config/user_agents.php $DEPLOYPATH2
    - /bin/cp -R /home/drynegr1/gitrepo/application/controllers $DEPLOYPATH3
    - /bin/cp -R /home/drynegr1/gitrepo/application/core $DEPLOYPATH3
    - /bin/cp -R /home/drynegr1/gitrepo/application/helpers $DEPLOYPATH3
    - /bin/cp -R /home/drynegr1/gitrepo/application/hooks $DEPLOYPATH3
    - /bin/cp -R /home/drynegr1/gitrepo/application/language $DEPLOYPATH3
    - /bin/cp -R /home/drynegr1/gitrepo/application/libraries $DEPLOYPATH3
    - /bin/cp -R /home/drynegr1/gitrepo/application/logs $DEPLOYPATH3
    - /bin/cp -R /home/drynegr1/gitrepo/application/models $DEPLOYPATH3
    - /bin/cp -R /home/drynegr1/gitrepo/application/third_party $DEPLOYPATH3
    - /bin/cp -R /home/drynegr1/gitrepo/application/views $DEPLOYPATH3
    - /bin/cp -R /home/drynegr1/gitrepo/application/.htaccess $DEPLOYPATH3
    - /bin/cp -R /home/drynegr1/gitrepo/application/.index.html $DEPLOYPATH3
    - /bin/cp -R /home/drynegr1/gitrepo/assets $DEPLOYPATH
    - /bin/cp -R /home/drynegr1/gitrepo/system $DEPLOYPATH
    - /bin/cp -R /home/drynegr1/gitrepo/index.php $DEPLOYPATH
    - /bin/cp -R /home/drynegr1/gitrepo/license.txt $DEPLOYPATH
    - /bin/cp -R /home/drynegr1/gitrepo/README.md $DEPLOYPATH